# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='modify_date',
            new_name='modify_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modify_date',
            new_name='modify_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='post'),
        ),
    ]
